
- name: Download Prometheus arm7
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.linux-armv7.tar.gz
    dest: /tmp/prometheus.tar.gz
  when: ansible_facts['architecture'] == "armv7l"

- name: Download Prometheus arm64
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.linux-arm64.tar.gz
    dest: /tmp/prometheus.tar.gz
  when: ansible_facts['architecture'] == "aarch64"


- name: Create Prometheus folder in opt
  become: yes
  file:
    path: /usr/bin/prometheus
    state: directory
    mode: '0777'

- name: Extract Prometheus
  become: yes
  unarchive:
     src: /tmp/prometheus.tar.gz
     dest: /usr/bin/prometheus
     remote_src: yes

- name: Create Prometheus Service File
  become: yes
  file:
      path: /etc/systemd/system/prometheus.service
      state: touch

- name: Create Prometheus data folder in opt
  become: yes
  file:
    path: /usr/bin/prometheus/prometheus/data
    state: directory
    mode: '0777'

- name: Edit Prometheus Service File
  become: yes
  blockinfile:
      path: /etc/systemd/system/prometheus.service
      marker: ""
      block: |
        [Unit]
        Description=Prometheus Server
        Documentation=https://prometheus.io/docs/introduction/overview/
        After=network-online.target

        [Service]
        User=ubuntu
        Restart=on-failure

        ExecStart=/usr/bin/prometheus/prometheus/prometheus \
        --config.file=/usr/bin/prometheus/prometheus/prometheus.yml \
        --storage.tsdb.path=/usr/bin/prometheus/prometheus/data

        [Install]
        WantedBy=multi-user.target

- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

- name: Start Prometheus service
  become: yes
  service:
    name: prometheus
    enabled: yes
    state: started

