
- name: Download Node exporter arm7
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-armv7.tar.gz
    dest: /tmp/node_exporter.tar.gz
  when: ansible_facts['architecture'] == "armv7l"

- name: Download Node exporter arm64
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-arm64.tar.gz
    dest: /tmp/node_exporter.tar.gz
  when: ansible_facts['architecture'] == "aarch64"

- name: Create Node exporter folder in opt
  become: yes
  file:
    path: /usr/bin/nodeexporter
    state: directory
    mode: '0777'

- name: Extract Node exporter
  become: yes
  unarchive:
     src: /tmp/node_exporter.tar.gz
     dest: /usr/bin/nodeexporter
     remote_src: yes

- name: Create Node exporter Service File
  become: yes
  file:
      path: /etc/systemd/system/nodeexporter.service
      state: touch

- name: Edit Node exporter Service File
  become: yes
  blockinfile:
      path: /etc/systemd/system/nodeexporter.service
      marker: ""
      block: |
        [Unit]
        Description=Node Exporter
        Documentation=https://prometheus.io/
        After=network-online.target

        [Service]
        User=ubuntu
        Restart=on-failure

        [Service]
        User=ubuntu
        ExecStart=/usr/bin/nodeexporter/node_exporter/node_exporter

        [Install]
        WantedBy=multi-user.target

- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

- name: Start Node exporter service
  become: yes
  service:
    name: nodeexporter
    enabled: yes
    state: started

