---
- name: Download Grafana 32bit
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.1.5_armhf.deb 
    dest: /tmp/grafana.deb
  when: ansible_facts['architecture'] == "armv7l" 

- name: Download Grafana 64bit
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.1.5_arm64.deb
    dest: /tmp/grafana.deb
  when: ansible_facts['architecture'] == "aarch64" 

- name: Install adduser (Grafana pre-req)
  become: yes
  apt:
    name: adduser
    state: present

- name: Install libfontconfig1 (Grafana pre-req)
  become: yes
  apt:
    name: libfontconfig1
    state: present

- name: Install Grafana
  become: yes
  apt:
    deb: /tmp/grafana.deb

- name: Enable Grafana Service
  become: yes
  service:
    name: grafana-server
    state: started
    enabled: yes
