---
- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Remove "grafana" package
  become: yes
  apt:
    name: grafana
    state: absent
