

- name: Delete Prometheus folder in opt
  become: yes
  file:
    path: /usr/bin/prometheus
    state: absent


- name: Delete Prometheus Service File
  become: yes
  file:
      path: /etc/systemd/system/prometheus.service
      state: absent

- name: Delete Prometheus data folder in opt
  become: yes
  file:
    path: /usr/bin/prometheus/prometheus/data
    state: absent


- name: Stop Prometheus service
  become: yes
  service:
    name: prometheus
    enabled: no
    state: stopped

- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

